### ISSUE TITLE
Breaking a mob spawner will not drop the spawner with silk touch pickaxe

### ISSUE THREAD

**Issue by Smeo00** [SkyBlockPE/Skyblock-Bugs#10]
Break a spawner with a silk ench pickaxe.
Spawner will not drop.
The silk effect still works on ores etc.

**Comment by ThatGeniusYT** [comment]
This issue is still happening for me. I broke all 3 of my spawners at once with a Silk g pic and none of them dropped.

**Comment by imjack** [comment]
Fixed, silk touch spawners for VIPs
