### ISSUE TITLE
Unable to strip wood block

### ISSUE THREAD

**Issue by ClownsMonocle** [SkyBlockPE/Skyblock-Bugs#105]
Issue: Unable to collect or make a stripped wood block using any axe in the server.
The error in chat says " Please wait for XX minutes and XX Seconds before usin your power ups. ". [Even](url) after waiting the said time, it still throws the same error when re-tried. Attached is screensht. I am accessing minecraft from phone. so single tap normally results in wood strip on any other server
![WhatsApp Image 2020-08-19 at 22 28 37](https://user-images.githubusercontent.com/69916758/90666792-893bd800-e26b-11ea-98f8-66628576ac86.jpeg)

**Comment by ItsMeCuby** [comment]
Stripped wood is not supported by servers host, 1.13+ blocks are not supported by servers host.

**Comment by SupremeMortal** [comment]
Yup, we don't support these blocks yet. It is something in the pipeline but it's still far off.
