### ISSUE TITLE
Vote Messages showing coding and not colored words

### ISSUE THREAD

**Issue by LuciferZone2137** [SkyBlockPE/Skyblock-Bugs#118]
![Screenshot_2021-01-27-13-05-20-919_com mojang minecraftpe](https://user-images.githubusercontent.com/78072806/105959592-1ba99880-60a2-11eb-9816-2ef689870bbd.jpg)

Coloured text were not showing on my screen idk about others when this guy/girl voted.

**Comment by imjack** [comment]
Fixed
