### ISSUE TITLE
Vote rewards not being given.

### ISSUE THREAD

**Issue by Smeo00** [SkyBlockPE/Skyblock-Bugs#12]
When you vote on any of the two good vote sites while logged off of sbpe, the vote rewards are not given to the player.
It seems the registered votes are being expired or there may be something cancelling the playerJoinEvent.
- raise a *valid* vote while logged off sbpe.
- wait <TBD - Time> (30 seconds is currently ok and the longest I've tested)
- log on sbpe
- check if vote rewards are given

**Comment by blackoes08** [comment]
yep same. have to be logged in to get the rewards

**Comment by imjack** [comment]
fixed
