### ISSUE TITLE
Can't craft Lapis Lazuli Blocks

### ISSUE THREAD

**Issue by Shuurai6762** [SkyBlockPE/Skyblock-Bugs#122]
![Screenshot_20210417-140839_Minecraft](https://user-images.githubusercontent.com/82696657/115103745-e6b52f80-9f86-11eb-8d0c-2f2aad7acf90.jpg)
![Screenshot_20210417-140808_Minecraft](https://user-images.githubusercontent.com/82696657/115103749-ecab1080-9f86-11eb-97af-0a60f0894de4.jpg)

**Comment by imjack** [comment]
fixed
