### ISSUE TITLE
Commands dont work

### ISSUE THREAD

**Issue by TheGreatCosmE** [SkyBlockPE/Skyblock-Bugs#17]
When i put /is spawn to go back to my island nothing happens, and when i used /tpa to teleport to my island with a staff, it said "that player isnt online" (i wrotte correctly the name)
Could you fix that issue?

**Comment by imjack** [comment]
any errors etc?

**Comment by TheGreatCosmE** [comment]
No more errors right now, but it is so annoying that i cant get out form my island because i couldnt get back later

El sáb., 13 de julio de 2019 1:46 p.m., Jack <notifications@github.com<mailto:notifications@github.com>> escribió:

any errors etc?

**Comment by imjack** [comment]
Username and device?

**Comment by TheGreatCosmE** [comment]
TRWcosmi and device is Alcatel pixi 4 (5010G)

El sáb., 13 de julio de 2019 2:12 p.m., Jack <notifications@github.com<mailto:notifications@github.com>> escribió:

Username and device?
