### ISSUE TITLE
Money Donation Failure

### ISSUE THREAD

**Issue by CorniestBoss** [SkyBlockPE/Skyblock-Bugs#21]
Some Days ago my friend by the username “SirDerpyBoi” gave me 100,000 in the money currency and it never came up I had the same amount before he gave me that money also it used his money and the notification came out in the chat but it never worked for me, so “SirDerpyBoi” lost 100,000 and I never gained that amount.

**Comment by imjack** [comment]
Unless proof and a working method can be given this cannot be fixed
