### ISSUE TITLE
Issue with setting homes

### ISSUE THREAD

**Issue by blackoes08** [SkyBlockPE/Skyblock-Bugs#23]
I am having an issue setting a home because chat says i have reached the max limit of homes, but i have no homes. Please note i am using windows 10, which may change how this problem is fixed.
 
![home 1](https://user-images.githubusercontent.com/52813823/61668859-41bbe300-ad1d-11e9-8da4-5d4ef12075e3.PNG)

![home 2](https://user-images.githubusercontent.com/52813823/61668860-41bbe300-ad1d-11e9-83dc-3a2bb2764cf2.PNG)

doing a command like /home list  returns an insufficient permissions message

**Comment by imjack** [comment]
Are you are VIP?

**Comment by blackoes08** [comment]
No, im not

**Comment by imjack** [comment]
Fixed
