### ISSUE TITLE
Items disappear after you put them in chest

### ISSUE THREAD

**Issue by ItsBeastPlayz** [SkyBlockPE/Skyblock-Bugs#27]
When 

you put items in your chest and a few seconds later it's gone you can't see them in the chest but when you break the chest all the items come out and its really annoying to keep breaking my chests

**Comment by imjack** [comment]
is this fixed?

**Comment by Smeo00** [comment]
Cannot recreate.
lack of detailed information.
May be due to #80 but there is insufficient detail in the original bug to tell and user is not responding to info request.
