### ISSUE TITLE
Crash When Crafting

### ISSUE THREAD

**Issue by McElwell** [SkyBlockPE/Skyblock-Bugs#29]
New players have been experiencing issues with crafting specifically those using the 'Classic' UI Profile. Sometimes, the item they crafted would revert back to it's previous raw state (for this I've given them a work around by not using the interface on the left) other times it freezes and crashes.

From my experience the issue mostly occurs when crafting in bulks (holding shift). 
 
![Crash](https://user-images.githubusercontent.com/52785327/62858245-b5845680-bcf1-11e9-800a-be5c750c057a.gif)

**Comment by imjack** [comment]
Not heard anything from this bug for awhile. If this bug still exists, please reopen
