### ISSUE TITLE
Windows 10 right clicking

### ISSUE THREAD

**Issue by VegeoStudios** [SkyBlockPE/Skyblock-Bugs#3]
When signs are interacted with or things are right clicked with a tool in hand, the interaction is spammed. Buying items from shop fill inventory and making paths triggers mcmmo.
![image](https://user-images.githubusercontent.com/45889580/60840158-174e1f80-a18c-11e9-98ce-75d4a9df9f16.png)

**Comment by imjack** [comment]
The mcmmo trigger can be fixed by SBPE, however the interaction spam is known. A patch by nukkit attempted to fix this awhile ago but players didn't like it.

**Comment by VegeoStudios** [comment]
How bout let the interaction trigger every half-second?

**Comment by Smeo00** [comment]
Fixed, right click no longer spams interaction.
(Tested on W10)
