### ISSUE TITLE
Enchanted books stuck in inventory

### ISSUE THREAD

**Issue by MarioisMLG** [SkyBlockPE/Skyblock-Bugs#31]
If you put 2+ enchanted books in a chest and throw them (during the chest is opened) and pick them up the enchanted books gets stacked instead of 1 by 1 and if you try to take it out,it doesn't work[http://imgur.com/gallery/HG6Ub3U]()

**Comment by imjack** [comment]
Explain in more detail. Step by step

**Comment by MarioisMLG** [comment]
If you put 2+ enchanted books in a chest and throw them (during the chest is opened) and pick them up the enchanted books gets stacked instead of 1 by 1 and if you try to take it out,it doesn't work

**Comment by imjack** [comment]
This should be fixed as for my latest nukkit push
