### ISSUE TITLE
Pshops bug

### ISSUE THREAD

**Issue by MarioisMLG** [SkyBlockPE/Skyblock-Bugs#36]
Amount doesn't show when your "Item" are 2 lines in your pshop.Example: 
[pbuy]
£1000.0
Green Glazed
Terracotta
Signs only have 4 lines the amount doesn't show even though it still works.This can lead to costumers getting scammed Example:
[pbuy]
£1000.0
Green Glazed
Terracotta
(if you put 0 on the "Amount")
Customers doesn't know that they just bought nothing for $1000.Here's a video of it https://streamable.com/dw7l0

**Comment by imjack** [comment]
fixed
