### ISSUE TITLE
Accacia leaves don't decompose

### ISSUE THREAD

**Issue by PGUStoked** [SkyBlockPE/Skyblock-Bugs#40]
Accacia leaves that are disconnected from their log should start decomposing but they simply remain in the air. When broken down they drop sticks and samplings as normal.

**Comment by YoavBerger** [comment]
Don't you need to break down ALL the wood from that same accasia tree for it do decompose?

**Comment by Smeo00** [comment]
Fixed, Acacia leaves now decompose and and drop saplings.
