### ISSUE TITLE
Water climb glitch when block is not filled with water but the corner attached to it is

### ISSUE THREAD

**Issue by PGUStoked** [SkyBlockPE/Skyblock-Bugs#42]
![giphy](https://user-images.githubusercontent.com/56491750/67480269-e40e9e00-f65f-11e9-903c-7d723955293d.gif)

**Comment by SupremeMortal** [comment]
Were you able to do the same in single player?

**Comment by PGUStoked** [comment]
![giphy (2)](https://user-images.githubusercontent.com/56491750/67564244-de2dc100-f722-11e9-8c69-ae30feca1415.gif)

Does not work in single player. not creative nor survival
@SupremeMortal

**Comment by SupremeMortal** [comment]
Ok, so this is a Nukkit related issue.

**Comment by PGUStoked** [comment]
This bug has been resolved with the last server reset.
