### ISSUE TITLE
Invisible Blocks

### ISSUE THREAD

**Issue by ItsMeKarla** [SkyBlockPE/Skyblock-Bugs#47]
So I was flying on my friend's island and suddenly crashed with some invisible blocks, one of my friends flew through them but something seems to be wrong

https://streamable.com/hemrp

https://streamable.com/k8ph6

**Comment by imjack** [comment]
can you break it?

**Comment by SupremeMortal** [comment]
Looks like a chunk related problem because the other player is sliding.

**Comment by imjack** [comment]
Appears to be gone? Reopen if this still is an issue
