### ISSUE TITLE
Spawners not working

### ISSUE THREAD

**Issue by ThatGeniusYT** [SkyBlockPE/Skyblock-Bugs#5]
Yesterday (July 8th) when I left there were cows in my spawners. When I came online today, though, the spawners were empty and I could not place any spawn eggs in it (I tried using Cow Spawn Eggs).
![Screenshot_2019-07-09-19-56-31](https://user-images.githubusercontent.com/52725479/60932915-bdca1b80-a285-11e9-833c-dfc9a0710468.png)

**Comment by imjack** [comment]
I've noticed this too. This is due to a nukkit NBT update. I suggest you don't waste any mob eggs until I fix this issue

**Comment by imjack** [comment]
Fixed
