### ISSUE TITLE
Food

### ISSUE THREAD

**Issue by ItsMeKarla** [SkyBlockPE/Skyblock-Bugs#50]
People can't eat

https://streamable.com/i9r7m

**Comment by PGUStoked** [comment]
I have the same problem. Food does not saturate your hunger. ./feed works for the vips

**Comment by SupremeMortal** [comment]
What platform are you on?
If someone knows reliable steps to reproduce this, please share.

**Comment by PGUStoked** [comment]
I'm on windows 10.

**Comment by PGUStoked** [comment]
I am able to eat at the /spawn island but not on my personal island. Eating at the spawn island also gives the eating particles to other players.

**Comment by imjack** [comment]
Fixed.
