### ISSUE TITLE
Torches not properly attaching to blocks

### ISSUE THREAD

**Issue by PGUStoked** [SkyBlockPE/Skyblock-Bugs#52]
Unable to attack torches to blocks nor N, E, S or W
Bug is for redstone and normal torches.
Playing on pc windows 10 version and placing torches on a block placed before the update.
I also tested it on new placed blocks still bugs.

![giphy](https://user-images.githubusercontent.com/56491750/68391311-9ddd3280-0167-11ea-9fa0-b3f58345b073.gif)

**Comment by SupremeMortal** [comment]
This is known. I'm working on a fix

**Comment by SupremeMortal** [comment]
This should be fixed in the next update.
