### ISSUE TITLE
Water appeared in glass panes and sometimes had the glass texture

### ISSUE THREAD

**Issue by spongebobsqrhed** [SkyBlockPE/Skyblock-Bugs#56]
![Screenshot_20191201-220402_Minecraft](https://user-images.githubusercontent.com/58441856/69985318-914ac080-1500-11ea-8f1a-68004c25a653.jpg)
To recreate tap on a glass pane with a water bucket and then place another pane next to it and then mine it.

**Comment by SupremeMortal** [comment]
Glass pane or glass block? The textures look like glass blocks.

**Comment by spongebobsqrhed** [comment]
Wdym?

**Comment by spongebobsqrhed** [comment]
Just glass

**Comment by spongebobsqrhed** [comment]
To recreate use panes

**Comment by SupremeMortal** [comment]
Fixed in next update
