### ISSUE TITLE
Player shops Debit money even when items cannot be given and items are lost.

### ISSUE THREAD

**Issue by Smeo00** [SkyBlockPE/Skyblock-Bugs#57]
With inventory full.
Make a purchase from a pshop sign.
Confirm balance is deducted.
Confirm Items have been removed from pshop chest
Confirm items are not recieved by player and have disappeared.

c.f. Player report...
"ArshleToday at 04:41
okay i just bought the spawner on smeo00's isle, and my inventory was full. so my cash was deducted, and i didnt get the spawner. i have a 30 sec clip regarding the same, but i cant send it here bcos file size. Dm if you want the video, ill be glad to help."
video link:
https://streamable.com/31ppq

**Comment by imjack** [comment]
fixed
