### ISSUE TITLE
Ranks

### ISSUE THREAD

**Issue by Max1999z** [SkyBlockPE/Skyblock-Bugs#60]
I am level 2670 and sky emporer is 2000 how ever I am at the emporer rank not sky emporer it’s really annoying cus my level it 2670 please fix ign Kingmaximoo04 and TheGoldenDoge01 is having the same problem
![image](https://user-images.githubusercontent.com/58820276/71618772-0de0c580-2bb9-11ea-9b51-b2e2cfe6dabf.jpg)

**Comment by imjack** [comment]
has this been fixed?

**Comment by imjack** [comment]
Assume to be fixed
