### ISSUE TITLE
Pvp blocks

### ISSUE THREAD

**Issue by TangentDuck427** [SkyBlockPE/Skyblock-Bugs#62]
When in pvp, if you break a wood block, it disapears, and if you place a block, it stays there. Recorded
Friday January 17th 10:38 AM

![20200117_102624_edited_1](https://user-images.githubusercontent.com/59990347/72625128-2f121780-3916-11ea-955a-853ce937d4cf.gif)

**Comment by imjack** [comment]
clientside
