### ISSUE TITLE
Can't place certain blocks

### ISSUE THREAD

**Issue by YoavBerger** [SkyBlockPE/Skyblock-Bugs#68]
You can place the villager- related blocks, such as looms, stone cutter, Gring stone and more (which means that if you bought a banner for 100k~ then you can't put patterns on it)

Also slight issue that some types of signs like birch signs can't be placed.

BTW I didn't buy a banner for 100k but some folks bidded more than that on it as banners can't be crafted due to a glitch.

**Comment by SupremeMortal** [comment]
These blocks are not implemented due to a limitation

**Comment by YoavBerger** [comment]
So will you add them or this is going to stay like this forever?
