### ISSUE TITLE
Sugar cane item

### ISSUE THREAD

**Issue by ghost** [SkyBlockPE/Skyblock-Bugs#75]
Someone had gave me 2 different types of sugar cane, not really sure but seems like a bug to me. (Not really sure how uploading images work here tried to attach them.)
![35977540-1FB3-4E02-B161-732F217325F8](https://user-images.githubusercontent.com/52635343/75381158-45f94180-58a6-11ea-973e-a0af88852e2e.png)
![E6D14E6A-F0C4-4E9C-BB12-B3B46E8964BD](https://user-images.githubusercontent.com/52635343/75381163-485b9b80-58a6-11ea-8179-2128daff5084.png)

**Comment by Smeo00** [comment]
Posted a video on Discord debugging#chat Sun 22/03 23:18 GMT showing how these are created.
Too sensitive to post it here.

**Comment by imjack** [comment]
Appears to be fixed
