### ISSUE TITLE
Entities on ground

### ISSUE THREAD

**Issue by ghost** [SkyBlockPE/Skyblock-Bugs#76]
Broke some blocks next to a chest to place a sea lanturn, the cobble which was in the empty space where I placed the lanturn pushed out onto the ground, but I can’t pick it up. 
https://streamable.com/063vi
(Wasn’t lagging)

**Comment by Smeo00** [comment]
Cannot reproduce.
This behaviour is consitent with a partially dropped connection.
(Symptoms of that include that you remain connected, can move around and can see chat scrolling, however you cant interact with anything in world, cannot see your own messages in chat and if you tp to a new location chunks will not load)
Relog and/or restart your minecraft if this occurs again.
