### ISSUE TITLE
My game isn’t loading 

### ISSUE THREAD

**Issue by yahirakeih** [SkyBlockPE/Skyblock-Bugs#78]
I have been unable to access the server for months, it continues to load

Video: https://streamable.com/uld0i

**Comment by Smeo00** [comment]
Not a valid bug, more of a support request.
Please supply your full gamer tag for debugging help.

**Comment by yahirakeih** [comment]
Name: Yahirakeih
I’m not banned someone told me that is a bug from iPhone

**Comment by imjack** [comment]
fixed
