### ISSUE TITLE
Inventory Issues and Water Transparency

### ISSUE THREAD

**Issue by McElwell** [SkyBlockPE/Skyblock-Bugs#8]
11/07/2019 

Items in the inventory cannot be moved to chests or anywhere else. 
Blocks and tools currently present in the hotbar can be placed and used respectively but cannot be moved to a different inventory space. 

Crafting anything with any of the resources available in your inventory reverts it back to it's previous state. (I.e. crafting a gold block with 9 gold ingots will successfully create the gold block but will revert back to it's original state of 9 gold ingots after a second.)

Water is transparent but is a minor issue. 

Thanks! 
![BugGif](https://user-images.githubusercontent.com/52785327/61048571-18748c00-a3da-11e9-9432-ffe495c9a5aa.gif)

**Comment by imjack** [comment]
Can you relog and see if this bug stops?

**Comment by McElwell** [comment]
Relogged, problem still persists.

**Comment by imjack** [comment]
Run the command /suicide and try?

**Comment by McElwell** [comment]
Ran the command, died - problems persist unfortunately. 
Did it twice for good measure.

**Comment by imjack** [comment]
Windows 10 right?

**Comment by McElwell** [comment]
Yes

**Comment by Smeo00** [comment]
I cannot recreate this on W10, so it is a glitch rather than a bug.

**Comment by blackoes08** [comment]
water glitch is still a problem

**Comment by Smeo00** [comment]
1 problem 1 bug report! do not add multiple problems to a single report.
