### ISSUE TITLE
Can't go in my island

### ISSUE THREAD

**Issue by MrHax88** [SkyBlockPE/Skyblock-Bugs#88]
Hello staff, I have a problem with my island, i set the setspawn of my island in a wood slabe et now, when a press the command "/is spawn", i glitch and fall in the void.

I think you just need to tp me derecly in my island and just reset my spawnpoint. 
My speudo is MrHax88 in game

Thanks for your help :D

**Comment by imjack** [comment]
Appears to be fixed
