### ISSUE TITLE
Visual damage gague in hotbar showing full durability.

### ISSUE THREAD

**Issue by Smeo00** [SkyBlockPE/Skyblock-Bugs#9]
The hotbar is showing known damaged tools with full durability.
The damage is recorded on the actual tool but not shown on the damage bar for the tool.
The tool will still break eventually, even though the bar still shows full dura.
![Minecraft 11_07_2019 18_08_43](https://user-images.githubusercontent.com/24555756/61071002-dd894d00-a407-11e9-8242-b419e256b97d.png)

**Comment by imjack** [comment]
fixed
