### ISSUE TITLE
Some vote events are recieved but no rewards are given.

### ISSUE THREAD

**Issue by Smeo00** [SkyBlockPE/Skyblock-Bugs#90]
Some vote events (very few) are not being processed.
Have eliminated voting errors as event is recieved from pocketvote.
Have eliminated full inv on event processing.
Logs show 2 of 2 Vote event recieved but only one actioned.
Not related to #70

**Comment by Xp-Sand** [comment]
I have this problem

**Comment by imjack** [comment]
I'm aware of one cause, due to spaces in names. Should be fixed later today.

**Comment by Xp-Sand** [comment]
> I'm aware of one cause, due to spaces in names. Should be fixed later today.

I had doubted that its could have been this, but why does it happen that now

**Comment by imjack** [comment]
Previous space issue appears to be fixed. Current issue is players auto adding a space to the end due to phones auto fill
